language: go

go:
 - 1.7.5

install:
# Run random command to prevent run go get
- pwd

script:
 - go test -race $(go list ./... | grep -v /vendor/)
 
after_success:
 - curl --request POST "https://goreportcard.com/checks" --data "repo=github.com/artemnikitin/qa-slack-bot"
